Name: Abseil
Description: links abseil fully.
Version: null

Requires: >
    absl_absl_check
    absl_absl_log
    absl_absl_vlog_is_on
    absl_algorithm
    absl_algorithm_container
    absl_any
    absl_any_invocable
    absl_atomic_hook
    absl_bad_any_cast
    absl_bad_optional_access
    absl_bad_variant_access
    absl_base
    absl_base_internal
    absl_bind_front
    absl_bits
    absl_bounded_utf8_length_sequence
    absl_btree
    absl_charset
    absl_check
    absl_city
    absl_civil_time
    absl_cleanup
    absl_cleanup_internal
    absl_common_policy_traits
    absl_compare
    absl_compressed_tuple
    absl_config
    absl_container_common
    absl_container_memory
    absl_cord
    absl_cord_internal
    absl_cordz_functions
    absl_cordz_handle
    absl_cordz_info
    absl_cordz_sample_token
    absl_cordz_statistics
    absl_cordz_update_scope
    absl_cordz_update_tracker
    absl_core_headers
    absl_crc32c
    absl_crc_cord_state
    absl_crc_cpu_detect
    absl_crc_internal
    absl_debugging
    absl_debugging_internal
    absl_decode_rust_punycode
    absl_demangle_internal
    absl_demangle_rust
    absl_die_if_null
    absl_dynamic_annotations
    absl_endian
    absl_errno_saver
    absl_examine_stack
    absl_exponential_biased
    absl_failure_signal_handler
    absl_fast_type_id
    absl_fixed_array
    absl_flags
    absl_flags_commandlineflag
    absl_flags_commandlineflag_internal
    absl_flags_config
    absl_flags_internal
    absl_flags_marshalling
    absl_flags_parse
    absl_flags_path_util
    absl_flags_private_handle_accessor
    absl_flags_program_name
    absl_flags_reflection
    absl_flags_usage
    absl_flags_usage_internal
    absl_flat_hash_map
    absl_flat_hash_set
    absl_function_ref
    absl_graphcycles_internal
    absl_has_ostream_operator
    absl_hash
    absl_hash_container_defaults
    absl_hash_function_defaults
    absl_hash_policy_traits
    absl_hashtable_control_bytes
    absl_hashtable_debug
    absl_hashtable_debug_hooks
    absl_hashtablez_sampler
    absl_inlined_vector
    absl_inlined_vector_internal
    absl_int128
    absl_iterator_traits_internal
    absl_iterator_traits_test_helper_internal
    absl_kernel_timeout_internal
    absl_layout
    absl_leak_check
    absl_log
    absl_log_entry
    absl_log_flags
    absl_log_globals
    absl_log_initialize
    absl_log_internal_append_truncated
    absl_log_internal_check_impl
    absl_log_internal_check_op
    absl_log_internal_conditions
    absl_log_internal_config
    absl_log_internal_flags
    absl_log_internal_fnmatch
    absl_log_internal_format
    absl_log_internal_globals
    absl_log_internal_log_impl
    absl_log_internal_log_sink_set
    absl_log_internal_message
    absl_log_internal_nullguard
    absl_log_internal_nullstream
    absl_log_internal_proto
    absl_log_internal_strip
    absl_log_internal_structured
    absl_log_internal_structured_proto
    absl_log_internal_voidify
    absl_log_severity
    absl_log_sink
    absl_log_sink_registry
    absl_log_streamer
    absl_log_structured
    absl_low_level_hash
    absl_malloc_internal
    absl_memory
    absl_meta
    absl_no_destructor
    absl_node_hash_map
    absl_node_hash_set
    absl_node_slot_policy
    absl_non_temporal_arm_intrinsics
    absl_non_temporal_memcpy
    absl_nullability
    absl_numeric
    absl_numeric_representation
    absl_optional
    absl_overload
    absl_periodic_sampler
    absl_poison
    absl_prefetch
    absl_pretty_function
    absl_random_bit_gen_ref
    absl_random_distributions
    absl_random_internal_distribution_caller
    absl_random_internal_distribution_test_util
    absl_random_internal_entropy_pool
    absl_random_internal_fast_uniform_bits
    absl_random_internal_fastmath
    absl_random_internal_generate_real
    absl_random_internal_iostream_state_saver
    absl_random_internal_mock_helpers
    absl_random_internal_nonsecure_base
    absl_random_internal_pcg_engine
    absl_random_internal_platform
    absl_random_internal_randen
    absl_random_internal_randen_engine
    absl_random_internal_randen_hwaes
    absl_random_internal_randen_hwaes_impl
    absl_random_internal_randen_slow
    absl_random_internal_salted_seed_seq
    absl_random_internal_seed_material
    absl_random_internal_traits
    absl_random_internal_uniform_helper
    absl_random_internal_wide_multiply
    absl_random_random
    absl_random_seed_gen_exception
    absl_random_seed_sequences
    absl_raw_hash_map
    absl_raw_hash_set
    absl_raw_hash_set_resize_impl
    absl_raw_logging_internal
    absl_sample_recorder
    absl_scoped_set_env
    absl_span
    absl_spinlock_wait
    absl_stacktrace
    absl_status
    absl_statusor
    absl_str_format
    absl_str_format_internal
    absl_strerror
    absl_string_view
    absl_strings
    absl_strings_internal
    absl_symbolize
    absl_synchronization
    absl_throw_delegate
    absl_time
    absl_time_zone
    absl_tracing_internal
    absl_type_traits
    absl_utf8_for_code_point
    absl_utility
    absl_variant
    absl_vlog_config_internal
    absl_vlog_is_on
    absl_weakly_mixed_integer
