Name: User building flags
Description: flags specified in judge.
Version: null

Requires: ac_user_basic ac_user_extra ac_user_library

variant:
    clang:
        Cflags: >
            std.pcm
            std.compat.pcm
