Name: Basic build flags
Description: common flags both for build and for judge
Version: null

Cflags: >
    -std=gnu++23

variant:
    gcc:
        Libs: >
            -L${install_dir}/lib64
            -Wl,-R${install_dir}/lib64

    clang:
        Cflags: >
            -fuse-ld=lld

            -stdlib=libc++

            -rtlib=compiler-rt
            -unwindlib=libunwind

        Libs: >
            -Wl,-R${install_dir}/lib/x86_64-unknown-linux-gnu
            -Wl,-R${install_dir}/lib/clang/20/lib/x86_64-unknown-linux-gnu
