Name: Basic user flags
Description: essential flags for judge
Version: null

Requires: ac_basic

Cflags: >
    -DONLINE_JUDGE
    -DATCODER

    -Wall
    -Wextra

    -O2

Libs: >
    -Wl,--as-needed

variant:
    gcc:
        Cflags: >
            -fmodules

    clang:
        Cflags: >
            -fprebuilt-module-path=.
